apiVersion: v1
kind: Namespace
metadata:
  name: as3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as3-deployment
  namespace: as3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-as3
  template:
    metadata:
      labels:
        app: my-as3
    spec:
      containers:
      - name: as3
        image: cloudadc/as3-mock:0.5
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: as3-service
  namespace: as3
spec:
  type: NodePort
  selector:
    app: my-as3
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30443
