apiVersion: v1
kind: Pod
metadata:
  name: as3-svc
  labels:
    app: my-as3
spec:
  containers:
    - name: as3
      image: cloudadc/as3-mock:0.5
      ports:
        - containerPort: 443
  restartPolicy: Always
