apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: nginx-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: cloudadc/cafe:2.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: nginx-svc
  namespace: nginx-gw
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30007
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
