/*
This test is simulate the as3 Agent behavior.

1. as3 Agent initialization:
 1. TestIsBigIPAppServicesAvailable()
 2. TestPartitionClean()
 3. TestGetBigipRegKey()
*/
package agent

import (
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"

	cisAgent "github.com/kylinsoong/bigip-ctlr/pkg/agent"
	"github.com/kylinsoong/bigip-ctlr/pkg/appmanager"
)

var (
	appMgr     appmanager.Manager
	httpClient *http.Client
)

type (
	as3Declaration     string
	as3Control         as3JSONWithArbKeys
	as3Tenant          as3JSONWithArbKeys
	as3Application     as3JSONWithArbKeys
	as3JSONWithArbKeys map[string]interface{}
)

type config struct {
	data      string
	as3APIURL string
}

func createHTTPClient() *http.Client {
	rootCAs, _ := x509.SystemCertPool()
	certs := []byte("")
	if ok := rootCAs.AppendCertsFromPEM(certs); !ok {

	}

	tr := &http.Transport{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
			RootCAs:            rootCAs,
		},
	}

	timeoutLarge := 60 * time.Second
	httpClient = &http.Client{
		Transport: tr,
		Timeout:   timeoutLarge,
	}
	return httpClient
}

func httpReq(request *http.Request) (*http.Response, map[string]interface{}) {
	httpResp, err := httpClient.Do(request)
	if err != nil {
		fmt.Printf("[AS3] REST call error: %v ", err)
		os.Exit(1)
	}

	defer httpResp.Body.Close()

	body, err := ioutil.ReadAll(httpResp.Body)
	if err != nil {
		fmt.Printf("[AS3] REST call response error: %v ", err)
		os.Exit(1)
	}
	var response map[string]interface{}
	err = json.Unmarshal(body, &response)
	if err != nil {
		fmt.Printf("[AS3] Response body unmarshal failed: %v\n", err)
		os.Exit(1)
	}
	return httpResp, response
}

func TestCreateAgent(t *testing.T) {
	var err error
	agent := "as3"
	appMgr.AgentCIS, err = cisAgent.CreateAgent(agent)
	if err != nil {
		t.Logf("[INIT] unable to create agent %v error: err: %+v", agent, err)
		os.Exit(1)
	}
	t.Logf("type of : %s", reflect.TypeOf(appMgr.AgentCIS))
}

/*
The main AgentCIS.Init() logic is to verify the whether BIG-IP AS3 is available via execute the

	https://192.168.45.52/mgmt/shared/appsvcs/info

and check the respone body, and extract the as3 version, if the version is expected version, then the BIG-IP AS3 is available.

# Use the curl to simulate the process

% curl -s -k -u "admin:admin" -X GET https://192.168.45.52/mgmt/shared/appsvcs/info

	{
	  "version": "3.36.1",
	  "release": "1",
	  "schemaCurrent": "3.36.0",
	  "schemaMinimum": "3.0.0"
	}
*/
func TestIsBigIPAppServicesAvailable(t *testing.T) {

	url := "https://192.168.45.52/mgmt/shared/appsvcs/info"
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		t.Logf("[AS3] Creating new HTTP request error: %v ", err)
		os.Exit(1)
	}
	t.Logf("[AS3] posting GET BIGIP AS3 Version request on %v", url)

	req.SetBasicAuth("admin", "admin")

	httpClient = createHTTPClient()

	httpResp, responseMap := httpReq(req)

	t.Logf("httpResp: %v", httpResp)
	t.Logf("response: %v", responseMap)

	as3VersionStr := responseMap["version"].(string)
	as3versionreleaseStr := responseMap["release"].(string)
	as3SchemaVersion := responseMap["schemaCurrent"].(string)
	t.Logf("as3VersionStr: %s", as3VersionStr)
	t.Logf("as3versionreleaseStr: %s", as3versionreleaseStr)
	t.Logf("as3SchemaVersion: %s", as3SchemaVersion)

}

var baseAS3Config = `{
	"$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/%s/as3-schema-%s.json",
	"class": "AS3",
	"declaration": {
	  "class": "ADC",
	  "schemaVersion": "%s",
	  "id": "urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d",
	  "label": "CIS Declaration",
	  "remark": "Auto-generated by CIS",
	  "controls": {
		 "class": "Controls",
		 "userAgent": "CIS Configured AS3"
	  }
	}
  }
`

/*
This function will create a empty as3 declaration file:

	{
	  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.36.1/as3-schema-3.36.1-1.json",
	  "class": "AS3",
	  "declaration": {
	    "class": "ADC",
	    "controls": {
	      "class": "Controls",
	      "userAgent": "CIS/v K8S/v 1.23.10"
	    },
	    "id": "urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d",
	    "k8s": {
	      "Shared": {
	        "class": "Application",
	        "template": "shared"
	      },
	      "class": "Tenant",
	      "defaultRouteDomain": 0
	    },
	    "label": "CIS Declaration",
	    "remark": "Auto-generated by CIS",
	    "schemaVersion": "3.36.0"
	  }
	}
*/
func createEmptyAS3Declaration() as3Declaration {
	var as3Config map[string]interface{}
	baseAS3ConfigEmpty := fmt.Sprintf(baseAS3Config, "3.36.1", "3.36.1-1", "3.36.0")
	_ = json.Unmarshal([]byte(baseAS3ConfigEmpty), &as3Config)
	decl := as3Config["declaration"].(map[string]interface{})
	controlObj := make(as3Control)
	controlObj["class"] = "Controls"
	controlObj["userAgent"] = "CIS/v K8S/v 1.23.10"
	decl["controls"] = controlObj
	partition := "k8s"
	tenantObj := make(as3Tenant)
	app := as3Application{}
	app["class"] = "Application"
	app["template"] = "shared"
	tenantObj["class"] = "Tenant"
	tenantObj["Shared"] = app
	tenantObj["defaultRouteDomain"] = 0
	decl[partition] = tenantObj
	data, _ := json.Marshal(as3Config)
	emptyAS3Declaration := as3Declaration(data)
	return emptyAS3Declaration
}

/*
The steps of partition clean:
 1. create a empty as3 declaration
 2. create HTTP POST request uss empty as3 declaration as body, and "/mgmt/shared/appsvcs/declare/k8s" as url
 3. create HTTP Client, execute HTTP POST Request
 4. verify the response, print response message

if use curl to simulate above steps it looks below:

% curl -s -k -u "admin:admin" -X POST -H "Content-Type: application/json" -d @$(pwd)/emptyAS3Declaration.json  https://192.168.45.52/mgmt/shared/appsvcs/declare/k8s

	{
	  "results": [
	    {
	      "code": 200,
	      "message": "no change",
	      "host": "localhost",
	      "tenant": "k8s",
	      "runTime": 893
	    }
	  ],
	  "declaration": {
	    "k8s": {
	      "Shared": {
	        "class": "Application",
	        "template": "shared"
	      },
	      "class": "Tenant",
	      "defaultRouteDomain": 0
	    },
	    "class": "ADC",
	    "controls": {
	      "class": "Controls",
	      "userAgent": "CIS/v K8S/v 1.23.10",
	      "archiveTimestamp": "2024-01-13T02:06:44.596Z"
	    },
	    "id": "urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d",
	    "label": "CIS Declaration",
	    "remark": "Auto-generated by CIS",
	    "schemaVersion": "3.36.0",
	    "updateMode": "selective"
	  }
	}
*/
func TestPartitionClean(t *testing.T) {

	emptyAS3Declaration := createEmptyAS3Declaration()
	t.Logf("emptyAS3Declaration: %v", emptyAS3Declaration)

	data := string(emptyAS3Declaration)
	url := "https://192.168.45.52/mgmt/shared/appsvcs/declare/k8s"
	cfg := config{
		data:      data,
		as3APIURL: url,
	}
	httpReqBody := bytes.NewBuffer([]byte(cfg.data))

	req, err := http.NewRequest("POST", cfg.as3APIURL, httpReqBody)
	if err != nil {
		t.Errorf("[AS3] Creating new HTTP request error: %v ", err)
	}
	t.Logf("[AS3] posting request to %v", cfg.as3APIURL)

	req.SetBasicAuth("admin", "admin")
	httpClient = createHTTPClient()
	httpResp, responseMap := httpReq(req)
	t.Logf("httpResp: %v", httpResp)
	t.Logf("response: %v", responseMap)

	results := (responseMap["results"]).([]interface{})
	for _, value := range results {
		v := value.(map[string]interface{})
		t.Logf("[AS3] Response from BIG-IP: code: %v, tenant: %v, message: %v, runTime: %v", v["code"], v["tenant"], v["message"], v["runTime"])
	}
}

/*
This steps is execute the HTTP GET to extract license key, it's sammiliar like the below curl

% curl -s -k -u "admin:admin" -X GET https://192.168.45.52/mgmt/tm/shared/licensing/registration | jq .registrationKey
"KVPKO-EBYPF-UFQQG-WYBNP-TXRHIMF"
*/
func TestGetBigipRegKey(t *testing.T) {

	url := "https://192.168.45.52//mgmt/tm/shared/licensing/registration"
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		t.Errorf("Creating new HTTP request error: %v ", err)
	}

	t.Logf("Posting GET BIGIP Reg Key request on %v", url)
	req.SetBasicAuth("admin", "admin")
	httpClient = createHTTPClient()
	httpResp, responseMap := httpReq(req)
	if httpResp == nil || responseMap == nil {
		t.Errorf("HTTP response nil")
	}
	if responseMap["registrationKey"] != nil {
		registrationKey := responseMap["registrationKey"].(string)
		t.Logf("registrationKey: %s", registrationKey)
	}
}
